use std::path::{Path, PathBuf};

use graphyn_core::ir::{Diagnostic, DiagnosticCategory, DiagnosticLevel, Language};
use tree_sitter::Tree;

#[derive(Debug, Clone)]
pub struct ParsedFile {
    pub file: String,
    pub language: Language,
    pub source: String,
    pub tree: Tree,
    pub diagnostics: Vec<Diagnostic>,
}

pub fn parse_python(source: &str) -> Result<Tree, String> {
    let mut parser = tree_sitter::Parser::new();
    parser
        .set_language(&tree_sitter_python::language())
        .map_err(|e| format!("failed to set Python language: {e}"))?;
    parser
        .parse(source, None)
        .ok_or_else(|| "tree-sitter returned no parse tree".to_string())
}

pub fn is_likely_generated(source: &str, path: &Path) -> bool {
    let first_line = source.lines().next().unwrap_or("").to_lowercase();
    if first_line.contains("generated")
        || first_line.contains("auto-generated")
        || first_line.contains("do not edit")
        || first_line.contains("code generated by")
    {
        return true;
    }

    let path_str = path.to_string_lossy().to_lowercase();
    if path_str.contains("generated") || path_str.contains(".pb.") {
        return true;
    }

    false
}

pub fn parse_file(root: &Path, path: &PathBuf) -> Result<ParsedFile, String> {
    let source = std::fs::read_to_string(path)
        .map_err(|e| format!("failed reading {}: {e}", path.display()))?;
    let rel = path
        .strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/");

    let mut diagnostics = Vec::new();

    if is_likely_generated(&source, path) {
        let tree = parse_python("")?;
        diagnostics.push(Diagnostic {
            level: DiagnosticLevel::Info,
            category: DiagnosticCategory::Skip,
            message: "skipped likely generated file".to_string(),
            file: Some(rel.clone()),
            line: None,
        });
        return Ok(ParsedFile {
            file: rel,
            language: Language::Python,
            source: String::new(),
            tree,
            diagnostics,
        });
    }

    let tree = match parse_python(&source) {
        Ok(t) => t,
        Err(_) => {
            diagnostics.push(Diagnostic {
                level: DiagnosticLevel::Error,
                category: DiagnosticCategory::Parse,
                message: "tree-sitter parse error".to_string(),
                file: Some(rel.clone()),
                line: None,
            });
            parse_python("")?
        }
    };

    Ok(ParsedFile {
        file: rel,
        language: Language::Python,
        source,
        tree,
        diagnostics,
    })
}
